name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |

            # Navigate to the project directory
            cd ~/strapi-deployment/strapi-project/

            # Verify the package.json file exists
            if [ ! -f "package.json" ]; then
              echo "package.json not found in ~/strapi-deployment. Exiting."
              exit 1
            fi

            git pull origin master
            npm install

            # Start or restart Strapi using PM2
            if pm2 list | grep -q "strapi"; then
              echo "Restarting Strapi process"
              pm2 restart strapi --update-env
            else
              echo "Starting Strapi process"
              pm2 start npm --name "strapi" -- run start
            fi

            # Check the PM2 logs
            pm2 logs strapi
